### ISSUE TITLE
关于 power.config 的重要细节，魔鬼就藏在这里

### ISSUE THREAD

**Issue by vladimirlv17** [googleweb/power-rule-plugin#1]
你好
ja-netfilter 与 JetBrains 配合得很好，但我在网上看到的所有信息都是关于这个产品的、 
都是关于这个产品的。
但我想尝试将 ja-netfilter 应用于其他程序。
比方说，有一个用 SHA RSA 格式签名的程序许可证文件，它的格式如下

Format=2
Type=professional
Name=Vladimir
Email=xxx@xxx.com
FreeUpdatesUntil=2099-08-08
Enterprise=true
SignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSign
SignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSignSign。  

我制作了 "public.key "和 "private.key"，并签署了许可证文件。
接下来我只需正确填写 power.conf 文件。

你能举个小例子说明你的插件是如何工作的吗？
如何在其中正确使用我的密钥？

"EQUAL, "+new BigInteger(1,data) - 我不知道？
         pub.getPublicExponent() - 我不知道？
         pub.getModulus() - 是否为 "private.key"？
         "->"+
         new BigInteger(1,result)+"\n------------------------");
如果有机会，请提供帮助

**Comment by googleweb** [comment]
我已经收到您的信件!

**Comment by googleweb** [comment]
这个插件就是给你生成替换签名的规则，data就是你生成的签名，比对输出有与你data一致的规则，写入到power.conf中即可。

**Comment by vladimirlv17** [comment]
我已将您的插件与 "power "插件连接。
我为所调查的程序配置了 ja-netfilter。
我得到了以下结果（数值是有条件的）
[Result]
EQUAL,x - value1
     ,y - 65537
     , z - value2
     ->
     fakeResult - value3
然后，我用这些值配置了 power.conf。
我只需要为我的程序获取注册密钥。
这些 x、z、fakeResult 值能帮我吗？
如何继续？

**Comment by googleweb** [comment]
这个插件不需要配置规则，这个插件输出的规则是为power插件服务的。你用你自己生成的许可证文件去注册程序，从控制台启动程序，这个插默认把规则输出到控制台，如果不是，你需要修改这个插件的源代码，把输出的内容写入到文件。运行程序前，确定为注册程序配置好了ja-netfilter环境。如果你判断不出哪条是你需要的规则的话，你就把控制台输出的规则都写入到power.conf文件，然后重新启动注册程序，保证新的规则生效，这时候再去用许可证文件注册程序，看看能否注册成功。如果还不成功，可能rsa密钥长度不对，可能生成许可证规则不对，可能用的不是RSA算法，等等。

**Comment by vladimirlv17** [comment]
如果这不是秘密，你能否透露如何获取有关
Java 程序使用的 RSA、DSA 密钥。
如何知道密钥的长度和算法？
对互联网上的一切资料、文献、资源都感兴趣、 
专门的脚本或程序。
