### ISSUE TITLE
DSA 算法规则

### ISSUE THREAD

**Issue by vladimirlv17** [googleweb/power-rule-plugin#2]
Hello!
我喜欢你的插件。
有可能为 DSA 算法添加规则吗？

**Comment by googleweb** [comment]
我已经收到您的信件!

**Comment by googleweb** [comment]
不好意思，暂时没有，DSA算法没有接触过，加密算法不了解。

**Comment by googleweb** [comment]
不好意思，暂时没有，DSA算法没有接触过，加密算法不了解。

**Comment by googleweb** [comment]
现在支持DSA了，你可以测试一下。 @vladimirlv17

**Comment by googleweb** [comment]
现在支持DSA了，你可以测试一下。 @vladimirlv17

**Comment by vladimirlv17** [comment]
文件参考：upload.ee/files/16920143/java-agent.tar.gz.html ***@***.***/0?redirect=https%3A%2F%2Fwww.upload.ee%2Ffiles%2F16920143%2Fjava-agent.tar.gz.html&recipient=cmVwbHkrQUc3NkRQQU5NSVFaRkNOVDVCTlJaUjZFVjZYUlZFVkJOSEhJUkNCN1lFQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by googleweb** [comment]
我已经收到您的信件!
